name: dieklingel-kiosk
version: 0.1.1+1
summary: The kiosk application for dieKlingel Core
description: A Ubuntu-Frame compatible kiosk snap for dieKlingel
confinement: strict
compression: lzo
grade: stable
base: core22

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  dieklingel-kiosk:
    command-chain: &_command-chain
      - bin/wayland-launch
    command: &_command bin/kiosk
    plugs: &_plugs
      - opengl
      - wayland
      - audio-playback
      - network
    extensions: &_extensions
      - gnome
    environment: &_environment
      XDG_DATA_HOME: $SNAP_USER_DATA
      XDG_DATA_DIRS: $SNAP/usr/share
      GDK_GL: gles
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/bin/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      DIEKLINGEL_HOME: $SNAP_USER_COMMON

  daemon:
    daemon: simple
    restart-delay: 3s
    restart-condition: always
    command-chain: *_command-chain
    command: *_command
    plugs: *_plugs
    extensions: *_extensions
    environment: *_environment

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: '3.12.0'
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
      ln -sf $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/dart $SNAPCRAFT_PART_INSTALL/usr/bin/dart
      export PATH="$SNAPCRAFT_PART_INSTALL/usr/bin:$PATH"
      flutter doctor
      flutter precache
    build-packages:
      - clang
      - cmake
      - curl
      - ninja-build
      - unzip
    override-prime: ''

  dieklingel-kiosk:
    plugin: nil
    source: .
    after:
      - flutter-git
    build-packages:
      - pkg-config
      - libgtk-3-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/lib
      flutter clean
      flutter pub get
      flutter build linux --release -v
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/

  # Some utility scripts for setting up the Wayland environment
  wayland-launch:
    plugin: dump
    source: wayland-launch
    override-build: |
      # The plugs needed to run Wayland. (wayland-launch checks them, setup.sh connects them)
      # You may add further plugs here if you want these options
      PLUGS="opengl wayland audio-playback network"
      sed --in-place "s/%PLUGS%/$PLUGS/g" $SNAPCRAFT_PART_BUILD/bin/wayland-launch
      sed --in-place "s/%PLUGS%/$PLUGS/g" $SNAPCRAFT_PART_BUILD/bin/setup.sh
      snapcraftctl build
    stage-packages:
      - inotify-tools
